# R-Type (Japan prototype) -- Irem M72 clone of rtype.
# Requires the parent rtype.zip set beside the clone for inherited graphics declarations.

[set]
schema = "mnemos-romset/1"
name   = "rtypejp"
parent = "rtype"
board  = "irem_m72"

[[region]]
name = "maincpu"
size = 0x100000

[[region.file]]
name   = "db_b1.1b"
offset = 0x00001
stride = 2
size   = 0x10000
crc32  = 0xc1865141

[[region.file]]
name   = "db_a1.3b"
offset = 0x00000
stride = 2
size   = 0x10000
crc32  = 0x5ad2bd90

[[region.file]]
name   = "db_b2.1c"
offset = 0x20001
stride = 2
size   = 0x10000
crc32  = 0xb4f6407e

[[region.file]]
name   = "db_a2.3c"
offset = 0x20000
stride = 2
size   = 0x10000
crc32  = 0x6098d86f

[[region.file]]
name   = "db_b2.1c"
offset = 0xE0001
stride = 2
size   = 0x10000
crc32  = 0xb4f6407e

[[region.file]]
name   = "db_a2.3c"
offset = 0xE0000
stride = 2
size   = 0x10000
crc32  = 0x6098d86f
