// adpcm_a port fidelity. The golden PCM block was generated by running the
// identical decode scenario (configure_channel0 below) through a standalone
// build of this chip's ADPCM step decoder.

#include "adpcm_a.hpp"

#include "chip_registry.hpp"
#include "state.hpp"

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <cstdint>
#include <span>
#include <vector>

namespace {

    using mnemos::chips::chip_class;
    using mnemos::chips::create_chip;
    using mnemos::chips::reset_kind;
    using mnemos::chips::state_reader;
    using mnemos::chips::state_writer;
    using mnemos::chips::audio::adpcm_a;

    // A small ADPCM nibble stream at ROM byte address 0x000100. The 16-bit
    // register address is the high word of a 24-bit ROM address (low 8 bits
    // implied zero), so start_addr 0x0001 maps to ROM byte 0x000100. 4 bytes /
    // 8 nibbles; end_addr 0x0100 (block end 0x0100FF) leaves the channel
    // decoding past the data into the zero-filled tail (the decoder runs until
    // the end address, not the data).
    std::vector<std::uint8_t> make_rom() {
        std::vector<std::uint8_t> rom(0x200, 0U);
        rom[0x100] = 0x12;
        rom[0x101] = 0x34;
        rom[0x102] = 0x56;
        rom[0x103] = 0x77;
        return rom;
    }

    // Configure channel 0: full individual level, both pans on, master TL = 0
    // (full volume), start_addr = 0x0001 (ROM byte 0x000100), end_addr = 0x0100
    // (block end 0x0100FF), then key it on via the $00 ON path.
    void configure_channel0(adpcm_a& chip) {
        chip.write_reg(adpcm_a::reg_tl, 0x00);               // master full volume
        chip.write_reg(adpcm_a::reg_ch_pan_level + 0, 0xDF); // L=1,R=1, level=0x1F
        chip.write_reg(adpcm_a::reg_ch_start_lo + 0, 0x01);
        chip.write_reg(adpcm_a::reg_ch_start_hi + 0, 0x00); // start_addr = 0x0001 -> ROM 0x000100
        chip.write_reg(adpcm_a::reg_ch_end_lo + 0, 0x00);
        chip.write_reg(adpcm_a::reg_ch_end_hi + 0, 0x01); // end_addr   = 0x0100 -> block 0x0100FF
        chip.write_reg(adpcm_a::reg_key, 0x01);           // ON, channel 0
    }

    // Golden output (interleaved L,R; L==R under full L+R pan) generated from
    // the standalone decoder for the scenario above.
    constexpr std::array<std::int16_t, 32> kGolden = {
        96,    96,    256,   256,   480,   480,   768,   768,   1168,  1168, 1952,
        1952,  3744,  3744,  8000,  8000,  8672,  8672,  9280,  9280,  9824, 9824,
        10320, 10320, 10768, 10768, 11184, 11184, 11552, 11552, 11888, 11888};

} // namespace

TEST_CASE("adpcm_a registers in the chip registry as an audio synth", "[adpcm_a][audio]") {
    auto chip = create_chip("yamaha.adpcm_a");
    REQUIRE(chip != nullptr);
    REQUIRE(chip->metadata().klass == chip_class::audio_synth);
}

TEST_CASE("adpcm_a reset clears state to a defined baseline", "[adpcm_a][audio]") {
    adpcm_a chip;
    chip.write_reg(adpcm_a::reg_tl, 0x2A);
    chip.write_reg(adpcm_a::reg_ch_pan_level + 0, 0xDF);
    chip.write_reg(adpcm_a::reg_key, 0x01); // key on channel 0

    chip.reset(reset_kind::power_on);

    // Every register reads back zero and the chip is silent.
    for (std::uint8_t i = 0; i < adpcm_a::reg_count; ++i) {
        INFO("reg " << static_cast<int>(i));
        REQUIRE(chip.read_reg(i) == 0x00);
    }
    chip.step();
    REQUIRE(chip.last_left() == 0);
    REQUIRE(chip.last_right() == 0);
}

TEST_CASE("adpcm_a register writes read back and decode KEY/TL", "[adpcm_a][audio]") {
    adpcm_a chip;
    chip.write_reg(adpcm_a::reg_tl, 0x3F);
    REQUIRE(chip.read_reg(adpcm_a::reg_tl) == 0x3F);
    chip.write_reg(adpcm_a::reg_ch_start_hi + 2, 0x55);
    REQUIRE(chip.read_reg(adpcm_a::reg_ch_start_hi + 2) == 0x55);
    // Out-of-range offset (>= reg_count) returns open bus and ignores writes.
    // Offsets $00..$2F are real (flat) register slots on the hardware register
    // file; only $30 and above are unmapped, so probe there.
    REQUIRE(chip.read_reg(adpcm_a::reg_count) == 0xFF);
    chip.write_reg(adpcm_a::reg_count, 0x12);
    REQUIRE(chip.read_reg(adpcm_a::reg_count) == 0xFF);

    // With no ROM set and no channel keyed on, the chip is silent.
    chip.step();
    REQUIRE(chip.last_left() == 0);
    REQUIRE(chip.last_right() == 0);
}

TEST_CASE("adpcm_a decodes ADPCM sample-for-sample like the reference", "[adpcm_a][audio]") {
    adpcm_a chip;
    const std::vector<std::uint8_t> rom = make_rom();
    chip.set_sample_rom(rom);
    configure_channel0(chip);

    std::array<std::int16_t, 32> buf{};
    chip.generate(buf);
    for (std::size_t i = 0; i < buf.size(); ++i) {
        INFO("sample " << i << (i % 2 == 0 ? " (L)" : " (R)"));
        REQUIRE(buf[i] == kGolden[i]);
    }
}

TEST_CASE("adpcm_a key-off (DUMP) silences a channel", "[adpcm_a][audio]") {
    adpcm_a chip;
    const std::vector<std::uint8_t> rom = make_rom();
    chip.set_sample_rom(rom);
    configure_channel0(chip);

    chip.step();
    REQUIRE(chip.last_left() != 0); // sounding from its start address

    // $00 with bit7 set is DUMP/OFF mode; low bits pick channels to silence.
    chip.write_reg(adpcm_a::reg_key, adpcm_a::key_dump_mask | 0x01);
    chip.step();
    REQUIRE(chip.last_left() == 0);
    REQUIRE(chip.last_right() == 0);
}

TEST_CASE("adpcm_a save_state/load_state round-trips bit-identically", "[adpcm_a][audio]") {
    adpcm_a a;
    const std::vector<std::uint8_t> rom = make_rom();
    a.set_sample_rom(rom);
    configure_channel0(a);
    // Advance a few samples so the decoder runtime state is non-trivial.
    std::array<std::int16_t, 10> warm{};
    a.generate(warm);

    std::vector<std::uint8_t> blob;
    state_writer writer(blob);
    a.save_state(writer);

    adpcm_a b;
    b.set_sample_rom(rom); // ROM is host-owned and not part of the state blob
    state_reader reader(blob);
    b.load_state(reader);
    REQUIRE(reader.ok());
    REQUIRE(reader.remaining() == 0U);

    // From the restored state both chips must produce identical output.
    std::array<std::int16_t, 32> from_a{};
    std::array<std::int16_t, 32> from_b{};
    a.generate(from_a);
    b.generate(from_b);
    REQUIRE(from_a == from_b);
}

TEST_CASE("adpcm_a audio capture counts and drains in stereo frames", "[adpcm_a][audio]") {
    adpcm_a chip;
    const std::vector<std::uint8_t> rom = make_rom();
    chip.set_sample_rom(rom);
    configure_channel0(chip); // an active, audible channel
    chip.enable_audio_capture(true);
    constexpr std::size_t frames = 10U;
    chip.tick(frames); // clock_divider defaults to 1 -> one (L,R) frame per cycle

    // pending_samples() is in stereo frames (pairs), matching the player's
    // add_source() contract -- NOT raw int16.
    REQUIRE(chip.pending_samples() == frames);

    std::array<std::int16_t, 16> buf{};
    const std::size_t got = chip.drain_samples(buf.data(), 3U);
    REQUIRE(got == 3U);
    REQUIRE(chip.pending_samples() == frames - 3U);
    bool any_nonzero = false; // an active channel must produce non-silent capture
    for (std::size_t i = 0; i < got * 2U; ++i) {
        any_nonzero = any_nonzero || (buf[i] != 0);
    }
    REQUIRE(any_nonzero);

    std::array<std::int16_t, 64> rest{};
    const std::size_t left = chip.drain_samples(rest.data(), 100U);
    REQUIRE(left == frames - 3U);
    REQUIRE(chip.pending_samples() == 0U);
}
