// scsp port fidelity vs the Emu reference. The golden PCM block was generated by
// running the reference synthesis math standalone through the identical scenario
// built in configure_slot0() below (see _golden_gen.cpp alongside this file).

#include "scsp.hpp"

#include "chip_registry.hpp"
#include "state.hpp"

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <cstdint>
#include <span>
#include <vector>

namespace {

    using mnemos::chips::chip_class;
    using mnemos::chips::create_chip;
    using mnemos::chips::reset_kind;
    using mnemos::chips::state_reader;
    using mnemos::chips::state_writer;
    using mnemos::chips::audio::scsp;

    // Build the golden generator's scenario directly through the slot-register
    // window: slot 0 plays a PCM8 ramp at $1000, OCT/FNS=0 (one wave sample per
    // output sample), forward loop LEA=28, full direct-send level, pan centred,
    // attack_rate=2 (period 8192 -> the attack envelope is frozen at its key-on
    // 0x280 value across the captured window), then KYONEX keys it on.
    void configure_slot0(scsp& chip) {
        const auto ram = chip.waveram();
        for (std::uint32_t i = 0; i < 32U; ++i) {
            ram[0x1000U + i] = static_cast<std::uint8_t>(i * 4U);
        }
        // Slot 0 register block. The first two bytes form the 16-bit CTL word
        // (r[0x00] = high byte, r[0x01] = low byte):
        //   CTL[12] KYONEX, CTL[11] KYONB -> r[0x00] bits 4, 3.
        //   CTL[6:5] LPCTL, CTL[4] PCM8B, CTL[3:0] SA[19:16] -> r[0x01].
        chip.write_reg(0x00, 0x00); // KYON cleared for now
        chip.write_reg(0x01, 0x30); // PCM8B=1 (bit4) + LPCTL=1 (bit5), SA[19:16]=0
        chip.write_reg(0x02, 0x10); // SA[15:8]
        chip.write_reg(0x03, 0x00); // SA[7:0]  -> SA = $001000
        chip.write_reg(0x04, 0x00); // LSA hi
        chip.write_reg(0x05, 0x00); // LSA = 0
        chip.write_reg(0x06, 0x00); // LEA hi
        chip.write_reg(0x07, 28);   // LEA = 28
        chip.write_reg(0x08, 0x00); // EG0 hi
        chip.write_reg(0x09, 0x02); // EG0 lo: attack_rate = 2
        chip.write_reg(0x0A, 0x00); // EG1 hi
        chip.write_reg(0x0B, 0x00); // EG1 lo: release_rate = 0
        chip.write_reg(0x0D, 0x00); // TL = 0 (unity)
        chip.write_reg(0x10, 0x00); // pitch hi (OCT/FNS = 0)
        chip.write_reg(0x11, 0x00); // pitch lo
        chip.write_reg(0x16, 0xE0); // DISDL = 7 (bits 7:5), DIPAN = 0
        // Raise KYONB + KYONEX on byte $00 to key the slot on (the edge-trigger
        // rescan keys every slot whose KYONB is set, then clears KYONEX).
        chip.write_reg(0x00, 0x08 | 0x10); // KYONB + KYONEX
    }

    // Generated by _golden_gen.cpp (the reference synthesis math, same scenario).
    constexpr std::array<std::int16_t, 64> kPcmGolden = {
        0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,  9,  10, 10,
        11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21,
        22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 0,  0,  0,  0,  1,  1,  2,  2,  3,  3};

} // namespace

TEST_CASE("scsp registers in the chip registry as an audio synth", "[scsp][audio]") {
    auto chip = create_chip("yamaha.scsp");
    REQUIRE(chip != nullptr);
    REQUIRE(chip->metadata().klass == chip_class::audio_synth);
}

TEST_CASE("scsp reset clears slot + register state to a defined baseline", "[scsp][audio]") {
    scsp chip;
    configure_slot0(chip);
    // Run a few samples so runtime state is non-trivial before the reset.
    std::array<std::int16_t, 16> warm{};
    chip.generate(warm);

    chip.reset(reset_kind::hard);
    // All slot registers read back zero and the chip is silent.
    for (std::uint16_t off = 0; off < scsp::slot_reg_window; ++off) {
        INFO("register offset " << off);
        REQUIRE(chip.read_reg(off) == 0);
    }
    chip.step();
    REQUIRE(chip.last_left() == 0);
    REQUIRE(chip.last_right() == 0);
}

TEST_CASE("scsp slot-register write decodes and a keyed voice sounds", "[scsp][audio]") {
    scsp chip;
    // A write reads back through the slot window.
    chip.write_reg(0x07, 28);
    REQUIRE(chip.read_reg(0x07) == 28);
    // Outside the modelled slot window returns open bus.
    REQUIRE(chip.read_reg(scsp::slot_reg_window) == 0xFF);

    configure_slot0(chip);
    // The keyed, audible slot produces a non-zero sample.
    std::array<std::int16_t, 8> buf{};
    chip.generate(buf);
    bool any_nonzero = false;
    for (const std::int16_t s : buf) {
        any_nonzero = any_nonzero || (s != 0);
    }
    REQUIRE(any_nonzero);
}

TEST_CASE("scsp generates PCM sample-for-sample like the reference", "[scsp][audio]") {
    scsp chip;
    configure_slot0(chip);
    std::array<std::int16_t, 64> buf{};
    chip.generate(buf);
    for (std::size_t i = 0; i < buf.size(); ++i) {
        INFO("sample " << i << (i % 2 == 0 ? " (L)" : " (R)"));
        REQUIRE(buf[i] == kPcmGolden[i]);
    }
}

TEST_CASE("scsp save_state/load_state round-trips bit-identically", "[scsp][audio]") {
    scsp a;
    configure_slot0(a);
    // Advance a few samples so runtime accumulator state is non-trivial.
    std::array<std::int16_t, 24> warm{};
    a.generate(warm);

    std::vector<std::uint8_t> blob;
    state_writer writer(blob);
    a.save_state(writer);

    scsp b;
    state_reader reader(blob);
    b.load_state(reader);
    REQUIRE(reader.ok());
    REQUIRE(reader.remaining() == 0U);

    // From the restored state both chips must produce identical output.
    std::array<std::int16_t, 64> from_a{};
    std::array<std::int16_t, 64> from_b{};
    a.generate(from_a);
    b.generate(from_b);
    REQUIRE(from_a == from_b);
}

TEST_CASE("scsp audio capture counts and drains in stereo frames", "[scsp][audio]") {
    scsp chip;
    configure_slot0(chip); // an enabled, audible slot
    chip.enable_audio_capture(true);
    constexpr std::size_t frames = 10U;
    chip.tick(frames); // clock_divider defaults to 1 -> one (L,R) frame per cycle

    // pending_samples() is in stereo frames (pairs) -- matching the player's
    // add_source() contract -- NOT raw int16.
    REQUIRE(chip.pending_samples() == frames);

    // Drain fewer pairs than queued: returns pairs, fills 2*pairs int16.
    std::array<std::int16_t, 16> buf{};
    const std::size_t got = chip.drain_samples(buf.data(), 3U);
    REQUIRE(got == 3U);
    REQUIRE(chip.pending_samples() == frames - 3U);

    // Draining past the end returns only what remains.
    std::array<std::int16_t, 64> rest{};
    const std::size_t left = chip.drain_samples(rest.data(), 100U);
    REQUIRE(left == frames - 3U);
    REQUIRE(chip.pending_samples() == 0U);
}
