#!/usr/bin/env python3
"""Generate CPS-2 game.toml ROM-set declarations from the authentic zips.

CPS-2 ROMs load by a fixed file-slot convention (the trailing number after the
last '.', plus an 'm' mask suffix), so the per-set toml is fully derivable from
the zip's central directory (names + CRC32 + sizes) -- no per-game table:

  slots 3-10 (no m) -> maincpu : the encrypted 68000 program (word-swapped)
  slots 1-2  (no m) -> audiocpu: the QSound Z80 (low 0x8000 fixed, rest banked
                                  from 0x10000)
  slots 11-12 (m)   -> qsound  : DL-1425 samples (word-swapped)
  slots 13-20 (m)   -> gfx     : word-lane interleaved (the board then unshuffles
                                  each 0x200000 bank at load)

The 20-byte board key is an external asset resolved at runtime from a
keys/<set>*.key sidecar (validated by decrypting the reset vector), so it is not
referenced here. SIMM-layout sets (a different ROM organisation) are skipped.

Usage: python scripts/gen_cps2_game_tomls.py <rom_dir> <out_dir> [set ...]
"""
import os
import sys
import zipfile

# slot -> (group, lane) for the standard word-lane gfx layout.
GFX_SLOT_LANE = {13: (0, 0), 15: (0, 2), 17: (0, 4), 19: (0, 6),
                 14: (1, 0), 16: (1, 2), 18: (1, 4), 20: (1, 6)}


def parse_slot(name):
    dot = name.rfind('.')
    if dot < 0:
        return None, False
    rest = name[dot + 1:]
    i = 0
    while i < len(rest) and rest[i].isdigit():
        i += 1
    if i == 0:
        return None, False
    return int(rest[:i]), (i < len(rest) and rest[i] in ('m', 'M'))


def entries(zip_path):
    out = []
    with zipfile.ZipFile(zip_path) as z:
        for info in z.infolist():
            if info.is_dir():
                continue
            out.append((os.path.basename(info.filename), info.CRC, info.file_size))
    return out


def hexc(crc):
    return "0x%08x" % (crc & 0xFFFFFFFF)


def emit_region(name, size, files):
    lines = ["", "[[region]]", 'name = "%s"' % name, "size = 0x%x" % size]
    for f in files:
        lines.append("")
        lines.append("[[region.file]]")
        for k, v in f:
            lines.append("%-13s = %s" % (k, v))
    return lines


def gen(set_name, zip_path):
    program, audio, qsound, gfx = [], [], [], []
    is_simm = False
    for name, crc, size in entries(zip_path):
        if "simm" in name.lower():
            is_simm = True
            continue
        slot, m = parse_slot(name)
        if slot is None:
            continue
        if 3 <= slot <= 10 and not m:
            program.append((slot, name, crc, size))
        elif slot in (1, 2) and not m:
            audio.append((slot, name, crc, size))
        elif slot in (11, 12) and m:
            qsound.append((slot, name, crc, size))
        elif 13 <= slot <= 20 and m:
            gfx.append((slot, name, crc, size))
    if is_simm:
        return None, "SIMM layout"
    if not program or not gfx:
        return None, "no program/gfx slots"

    out = ["# %s -- Capcom CPS2 (generated by scripts/gen_cps2_game_tomls.py)" % set_name,
           "#",
           "# The 20-byte board key is an external asset, resolved at runtime from a",
           "# keys/%s*.key sidecar (validated by decryption), never committed." % set_name,
           "", "[set]", 'schema = "mnemos-romset/1"',
           'name   = "%s"' % set_name, 'board  = "capcom_cps2"']

    # --- maincpu: program slots word-swapped, concatenated ---
    program.sort()
    off, files = 0, []
    for _slot, name, crc, size in program:
        files.append([("name", '"%s"' % name), ("offset", "0x%x" % off),
                      ("unit", "2"), ("swap", "true"), ("stride", "2"),
                      ("size", "0x%x" % size), ("crc32", hexc(crc))])
        off += size
    out += emit_region("maincpu", off, files)

    # --- audiocpu: low 0x8000 fixed, the rest banked from 0x10000 ---
    audio.sort()
    if audio:
        _slot, name, crc, size = audio[0]
        if size > 0x8000:
            files = [[("name", '"%s"' % name), ("offset", "0x0"),
                      ("source_offset", "0x0"), ("length", "0x8000"),
                      ("size", "0x%x" % size), ("crc32", hexc(crc))],
                     [("name", '"%s"' % name), ("offset", "0x10000"),
                      ("source_offset", "0x8000"),
                      ("length", "0x%x" % (size - 0x8000)),
                      ("size", "0x%x" % size), ("crc32", hexc(crc))]]
            region = 0x10000 + (size - 0x8000)
        else:
            files = [[("name", '"%s"' % name), ("offset", "0x0"),
                      ("size", "0x%x" % size), ("crc32", hexc(crc))]]
            region = max(size, 0x10000)
        out += emit_region("audiocpu", region, files)

    # --- qsound: slots 11/12 word-swapped, concatenated ---
    qsound.sort()
    if qsound:
        off, files = 0, []
        for _slot, name, crc, size in qsound:
            files.append([("name", '"%s"' % name), ("offset", "0x%x" % off),
                          ("unit", "2"), ("swap", "true"), ("stride", "2"),
                          ("size", "0x%x" % size), ("crc32", hexc(crc))])
            off += size
        out += emit_region("qsound", off, files)

    # --- gfx: word-lane interleave; group0 base 0, group1 base max(span,0x800000) ---
    group0_span = max((size * 4 for slot, _n, _c, size in gfx
                       if GFX_SLOT_LANE.get(slot, (9, 0))[0] == 0), default=0)
    group1_base = max(group0_span, 0x800000)
    group1_span = max((size * 4 for slot, _n, _c, size in gfx
                       if GFX_SLOT_LANE.get(slot, (9, 0))[0] == 1), default=0)
    gfx_size = group1_base + group1_span if group1_span else group0_span
    gfx.sort()
    files = []
    for slot, name, crc, size in gfx:
        if slot not in GFX_SLOT_LANE:
            return None, "unexpected gfx slot %d" % slot
        group, lane = GFX_SLOT_LANE[slot]
        base = 0 if group == 0 else group1_base
        files.append([("name", '"%s"' % name), ("offset", "0x%x" % (base + lane)),
                      ("unit", "2"), ("stride", "8"),
                      ("size", "0x%x" % size), ("crc32", hexc(crc))])
    out += emit_region("gfx", gfx_size, files)

    return "\n".join(out) + "\n", None


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    rom_dir, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    if len(sys.argv) > 3:
        names = sys.argv[3:]
    else:
        names = sorted(os.path.splitext(f)[0] for f in os.listdir(rom_dir)
                       if f.lower().endswith(".zip"))
    ok, skipped = 0, 0
    for name in names:
        zip_path = os.path.join(rom_dir, name + ".zip")
        if not os.path.isfile(zip_path):
            print("skip %s: no zip" % name)
            skipped += 1
            continue
        text, err = gen(name, zip_path)
        if text is None:
            print("skip %s: %s" % (name, err))
            skipped += 1
            continue
        with open(os.path.join(out_dir, name + ".toml"), "w", newline="\n") as fp:
            fp.write(text)
        print("wrote %s.toml" % name)
        ok += 1
    print("done: %d written, %d skipped" % (ok, skipped))
    return 0


if __name__ == "__main__":
    sys.exit(main())
