// okim6295 port fidelity vs the Emu reference. The golden sample blocks were
// generated by compiling+running the reference chip (chips/msm6295) through the
// identical synthetic scenarios reproduced in make_sample_rom() below.

#include "okim6295.hpp"

#include "chip_registry.hpp"
#include "state.hpp"

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <cstdint>
#include <span>
#include <vector>

namespace {

    using mnemos::chips::reset_kind;
    using mnemos::chips::state_reader;
    using mnemos::chips::state_writer;
    using mnemos::chips::audio::okim6295;

    // 256-byte sample ROM: a phrase table at offset 0 (8 bytes/phrase: 24-bit BE
    // start then end) plus two ADPCM nibble streams. Phrase 1 -> 0x40..0x4F,
    // phrase 2 -> 0x80..0x8F.
    std::array<std::uint8_t, 0x100> make_sample_rom() {
        std::array<std::uint8_t, 0x100> rom{};
        rom[8] = 0x00;
        rom[9] = 0x00;
        rom[10] = 0x40; // phrase 1 start 0x40
        rom[11] = 0x00;
        rom[12] = 0x00;
        rom[13] = 0x4F; // phrase 1 end   0x4F
        rom[16] = 0x00;
        rom[17] = 0x00;
        rom[18] = 0x80; // phrase 2 start 0x80
        rom[19] = 0x00;
        rom[20] = 0x00;
        rom[21] = 0x8F; // phrase 2 end   0x8F
        const std::array<std::uint8_t, 16> d1 = {0x11, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF,
                                                 0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF};
        for (std::size_t i = 0; i < d1.size(); ++i) {
            rom[0x40 + i] = d1[i];
        }
        const std::array<std::uint8_t, 16> d2 = {0x8F, 0x7E, 0x6D, 0x5C, 0x4B, 0x3A, 0x29, 0x18,
                                                 0x07, 0x16, 0x25, 0x34, 0x43, 0x52, 0x61, 0x70};
        for (std::size_t i = 0; i < d2.size(); ++i) {
            rom[0x80 + i] = d2[i];
        }
        return rom;
    }

    // Reference output: phrase 1 on channel 0 at full volume, 40 steps. The
    // 16-byte stream decodes to 32 samples (the predictor saturates to -32768
    // near the end), then the channel stops and the rest are silence.
    constexpr std::array<std::int16_t, 40> kPhrase1Golden = {
        96,     192,    352,   576,   864,   1264,   1984,   3472,  3264,   2688,
        1808,   688,    -624,  -2560, -5936, -12656, -11696, -9088, -5120,  -64,
        5872,   14624,  29824, 32752, 29824, 21840,  9728,   -5680, -23712, -32768,
        -32768, -32768, 0,     0,     0,     0,      0,      0,     0,      0};

    // Reference output: phrase 2 mixed on channel 1 (volume code 4 = 64/256) and
    // channel 2 (volume code 0 = full), 24 steps -- exercises summation across
    // channels, per-channel attenuation, and the +32767 mix clamp.
    constexpr std::array<std::int16_t, 24> kPhrase2MixGolden = {
        -40,  -640, 620,  -1740, 2480, -3680, 5380,  -5480, 7680,  -4280, 6580,  -720,
        5920, 2320, 5580, 4600,  5500, 17860, 22980, 32767, 32767, 32767, 32767, 32767};

} // namespace

TEST_CASE("okim6295 registers in the chip factory as an audio synth", "[okim6295][audio]") {
    auto chip = mnemos::chips::create_chip("oki.msm6295");
    REQUIRE(chip != nullptr);
    REQUIRE(chip->metadata().klass == mnemos::chips::chip_class::audio_synth);
    REQUIRE(chip->metadata().part_number == "MSM6295");
}

TEST_CASE("okim6295 decodes a phrase sample-for-sample like the reference", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);

    REQUIRE(chip.read_status() == 0xF0U); // idle: no channel busy
    chip.write_command(0x81U);            // play, phrase 1
    chip.write_command(0x10U);            // channel 0, volume code 0 (full)
    REQUIRE(chip.read_status() == 0xF1U); // channel 0 busy

    for (std::size_t i = 0; i < kPhrase1Golden.size(); ++i) {
        INFO("sample " << i);
        REQUIRE(chip.step() == kPhrase1Golden[i]);
    }
    REQUIRE(chip.read_status() == 0xF0U); // channel finished
}

TEST_CASE("okim6295 mixes two channels with per-channel volume like the reference",
          "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);

    chip.write_command(0x82U);               // play, phrase 2
    chip.write_command((0x2U << 4U) | 0x4U); // channel 1, volume code 4
    chip.write_command(0x82U);               // play, phrase 2
    chip.write_command((0x4U << 4U) | 0x0U); // channel 2, full volume
    REQUIRE(chip.read_status() == 0xF6U);    // channels 1 and 2 busy

    for (std::size_t i = 0; i < kPhrase2MixGolden.size(); ++i) {
        INFO("sample " << i);
        REQUIRE(chip.step() == kPhrase2MixGolden[i]);
    }
}

TEST_CASE("okim6295 ignores a retrigger on a busy channel", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);

    chip.write_command(0x81U); // phrase 1
    chip.write_command(0x10U); // channel 0
    for (int i = 0; i < 4; ++i) {
        chip.step();
    }
    // Attempt to restart channel 0 with phrase 2 mid-play: the busy channel must
    // keep decoding phrase 1, so the next outputs continue the phrase-1 sequence.
    chip.write_command(0x82U);
    chip.write_command(0x10U);
    for (std::size_t i = 4; i < 8; ++i) {
        INFO("post-retrigger sample " << i);
        REQUIRE(chip.step() == kPhrase1Golden[i]);
    }
}

TEST_CASE("okim6295 stop command silences the addressed channel", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);

    chip.write_command(0x81U);
    chip.write_command(0x10U); // channel 0 busy
    REQUIRE((chip.read_status() & 0x01U) != 0U);
    chip.write_command(0x08U); // stop: bit 3 -> channel 0
    REQUIRE((chip.read_status() & 0x01U) == 0U);
    REQUIRE(chip.read_status() == 0xF0U);
    REQUIRE(chip.step() == 0); // silent once stopped
}

TEST_CASE("okim6295 rejects out-of-bounds and malformed phrases", "[okim6295][audio]") {
    auto rom = make_sample_rom();

    SECTION("phrase whose table entry runs past the ROM does not start a channel") {
        okim6295 chip;
        chip.set_sample_rom(rom);
        chip.write_command(0x80U | 0x40U); // phrase 0x40: table at 0x200, past 0x100
        chip.write_command(0x10U);
        REQUIRE(chip.read_status() == 0xF0U);
    }

    SECTION("start >= end is rejected") {
        // Phrase 3 entry at offset 24: start 0x50, end 0x40 (inverted).
        rom[24] = 0x00;
        rom[25] = 0x00;
        rom[26] = 0x50;
        rom[27] = 0x00;
        rom[28] = 0x00;
        rom[29] = 0x40;
        okim6295 chip;
        chip.set_sample_rom(rom);
        chip.write_command(0x80U | 0x03U); // phrase 3
        chip.write_command(0x10U);
        REQUIRE(chip.read_status() == 0xF0U);
    }

    SECTION("end past the ROM is rejected") {
        // Phrase 4 entry at offset 32: start 0x40, end 0x200 (out of range).
        rom[32] = 0x00;
        rom[33] = 0x00;
        rom[34] = 0x40;
        rom[35] = 0x00;
        rom[36] = 0x02;
        rom[37] = 0x00;
        okim6295 chip;
        chip.set_sample_rom(rom);
        chip.write_command(0x80U | 0x04U); // phrase 4
        chip.write_command(0x10U);
        REQUIRE(chip.read_status() == 0xF0U);
    }
}

TEST_CASE("okim6295 with no sample ROM stays silent and idle", "[okim6295][audio]") {
    okim6295 chip; // no set_sample_rom
    chip.write_command(0x81U);
    chip.write_command(0x10U);
    REQUIRE(chip.read_status() == 0xF0U);
    REQUIRE(chip.step() == 0);
}

TEST_CASE("okim6295 generate duplicates the mono voice to both lanes", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);
    chip.write_command(0x81U);
    chip.write_command(0x10U);

    std::array<std::int16_t, 16> buf{};
    chip.generate(buf);
    for (std::size_t pair = 0; pair < buf.size() / 2U; ++pair) {
        REQUIRE(buf[pair * 2U] == buf[pair * 2U + 1U]);  // L == R
        REQUIRE(buf[pair * 2U] == kPhrase1Golden[pair]); // and matches the decode
    }
}

TEST_CASE("okim6295 capture sink queues stereo frames the divider gates", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);
    chip.set_clock_divider(4); // one native step per 4 input cycles
    chip.enable_audio_capture(true);
    chip.write_command(0x81U);
    chip.write_command(0x10U);

    chip.tick(40U); // 40 cycles / 4 = 10 native steps
    REQUIRE(chip.pending_samples() == 10U);

    std::array<std::int16_t, 20> out{};
    const std::size_t pairs = chip.drain_samples(out.data(), 10U);
    REQUIRE(pairs == 10U);
    REQUIRE(chip.pending_samples() == 0U);
    for (std::size_t i = 0; i < 10U; ++i) {
        REQUIRE(out[i * 2U] == out[i * 2U + 1U]);
        REQUIRE(out[i * 2U] == kPhrase1Golden[i]);
    }
}

TEST_CASE("okim6295 save_state/load_state round-trips mid-sample", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 a;
    a.set_sample_rom(rom);
    a.write_command(0x81U);
    a.write_command(0x10U);
    for (int i = 0; i < 9; ++i) { // stop mid-phrase, between byte boundaries
        a.step();
    }

    std::vector<std::uint8_t> blob;
    state_writer writer(blob);
    a.save_state(writer);

    okim6295 b;
    b.set_sample_rom(rom); // ROM is host-owned: the host re-attaches on load
    state_reader reader(blob);
    b.load_state(reader);
    REQUIRE(reader.ok());
    REQUIRE(reader.remaining() == 0U);

    for (std::size_t i = 9; i < kPhrase1Golden.size(); ++i) {
        INFO("post-restore sample " << i);
        const std::int16_t from_a = a.step();
        const std::int16_t from_b = b.step();
        REQUIRE(from_a == from_b);
        REQUIRE(from_b == kPhrase1Golden[i]);
    }
}

TEST_CASE("okim6295 save/load round-trips a negative predictor mid-phrase", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 a;
    a.set_sample_rom(rom);
    a.write_command(0x81U);
    a.write_command(0x10U);
    // By step 14 the predictor has gone negative (golden[13] == -2560), so this
    // snapshot proves the signed predictor survives the state round-trip.
    for (int i = 0; i < 14; ++i) {
        a.step();
    }

    std::vector<std::uint8_t> blob;
    state_writer writer(blob);
    a.save_state(writer);

    okim6295 b;
    b.set_sample_rom(rom);
    state_reader reader(blob);
    b.load_state(reader);
    REQUIRE(reader.ok());
    REQUIRE(reader.remaining() == 0U);

    for (std::size_t i = 14; i < kPhrase1Golden.size(); ++i) {
        INFO("post-restore sample " << i);
        REQUIRE(b.step() == kPhrase1Golden[i]);
    }
}

TEST_CASE("okim6295 pin7 selects the prescaler and native sample rate", "[okim6295][audio]") {
    okim6295 chip;
    chip.set_input_clock(1'000'000U);

    chip.set_pin7(true);
    REQUIRE(chip.pin7_high());
    REQUIRE(chip.native_sample_rate() == 1'000'000U / 132U);

    chip.set_pin7(false);
    REQUIRE_FALSE(chip.pin7_high());
    REQUIRE(chip.native_sample_rate() == 1'000'000U / 165U);
}

TEST_CASE("okim6295 save/load preserves pin7 and input clock", "[okim6295][audio]") {
    okim6295 a;
    a.set_pin7(false);
    a.set_input_clock(2'000'000U);

    std::vector<std::uint8_t> blob;
    state_writer writer(blob);
    a.save_state(writer);

    okim6295 b;
    state_reader reader(blob);
    b.load_state(reader);
    REQUIRE(reader.ok());
    REQUIRE(reader.remaining() == 0U);
    REQUIRE_FALSE(b.pin7_high());
    REQUIRE(b.native_sample_rate() == 2'000'000U / 165U);
}

TEST_CASE("okim6295 reg-write trace logs the raw command stream", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);

    auto* trace = chip.introspection().reg_writes();
    REQUIRE(trace != nullptr);
    std::vector<std::uint8_t> log;
    trace->install([&log](const mnemos::instrumentation::reg_write_event& e) {
        REQUIRE(e.port == 0U);
        log.push_back(e.value);
    });

    chip.write_command(0x81U); // play byte 1
    chip.write_command(0x10U); // play byte 2
    chip.write_command(0x08U); // stop channel 0
    REQUIRE(log == std::vector<std::uint8_t>{0x81U, 0x10U, 0x08U});
}

TEST_CASE("okim6295 audio source exports the decoded phrase waveforms", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);
    chip.set_pin7(true);
    chip.set_input_clock(1'000'000U);

    auto* audio = chip.introspection().audio();
    REQUIRE(audio != nullptr);
    const auto samples = audio->samples();
    REQUIRE(samples.size() == 2U); // only phrase 1 and phrase 2 are valid entries

    const auto& p1 = samples[0];
    REQUIRE(p1.name == "phrase_01");
    REQUIRE(p1.channels == 1);
    REQUIRE(p1.source_addr == 0x40U);
    REQUIRE(p1.sample_rate == 1'000'000U / 132U);
    // 16 bytes -> 32 nibbles -> 32 samples; at full volume the channel decode
    // equals the raw phrase decode, so the export matches the golden block.
    REQUIRE(p1.frames.size() == 32U);
    for (std::size_t i = 0; i < 32U; ++i) {
        INFO("phrase 1 export sample " << i);
        REQUIRE(p1.frames[i] == kPhrase1Golden[i]);
    }

    REQUIRE(samples[1].name == "phrase_02");
    REQUIRE(samples[1].source_addr == 0x80U);
}

TEST_CASE("okim6295 reset clears all channel and command state", "[okim6295][audio]") {
    const auto rom = make_sample_rom();
    okim6295 chip;
    chip.set_sample_rom(rom);
    chip.write_command(0x81U);
    chip.write_command(0x10U);
    chip.step();
    REQUIRE(chip.read_status() != 0xF0U);

    chip.reset(reset_kind::soft);
    REQUIRE(chip.read_status() == 0xF0U);
    REQUIRE(chip.step() == 0);
    // A half-consumed play command must not survive the reset.
    chip.write_command(0x10U); // would be byte 2 if a command were pending
    REQUIRE(chip.read_status() == 0xF0U);
}
