#!/usr/bin/env python3
"""Gate G9: lint YAML front matter and lifecycle state of governed documents.

Governed documents are docs/adr/{proposed,accepted,superseded}/*.md,
constitution/*.md (ARCH-*, STD-*, MNE-*), and the root CONSTITUTION.md.
See constitution/MNE-CTX-PLAN-001.md section 4.3 for the lifecycle contract.

Checks (each failure is a blocking finding):
  - front matter parses and carries id, title, status, version
  - status is one of: proposed, accepted, superseded, expired, rejected
  - directory placement matches status
  - accepted documents carry a `ratified` date
  - superseded documents name a successor in `superseded_by`
  - at most one accepted document per id
  - accepted bodies are not edited without a version bump (vs. --base ref)
  - docs/adr/INDEX.md matches the generated index (--check-index)

Notices (reported, never blocking):
  - proposed documents older than the expiry window (flipped by --fix-expiry)

Deterministic: same repository state in, same findings out. Exits 0/1.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
ADR_DIR = REPO / "docs" / "adr"
CONSTITUTION_DIR = REPO / "constitution"
EXPIRY_DAYS = 14  # D5 in MNE-CTX-PLAN-001
VALID_STATUS = {"proposed", "accepted", "superseded", "expired", "rejected"}
# Constitution modules keep their path across the lifecycle (the directory is
# the authority level); ADRs move between lifecycle directories.
STATUS_DIRS = {
    "proposed": {"proposed", "constitution", "."},
    "expired": {"proposed", "constitution", "."},
    "rejected": {"proposed", "constitution", "."},
    "accepted": {"accepted", "constitution", "."},
    "superseded": {"superseded", "constitution"},
}

FRONT_MATTER_RE = re.compile(r"\A---\n(.*?\n)---\n", re.DOTALL)


def governed_files() -> list[Path]:
    files: list[Path] = []
    for sub in ("proposed", "accepted", "superseded"):
        d = ADR_DIR / sub
        if d.is_dir():
            files.extend(sorted(d.glob("*.md")))
    if CONSTITUTION_DIR.is_dir():
        files.extend(
            p
            for p in sorted(CONSTITUTION_DIR.glob("*.md"))
            if re.match(r"(ARCH|STD|MNE)-", p.name)
        )
    root_index = REPO / "CONSTITUTION.md"
    if root_index.exists():
        files.append(root_index)
    return files


def split_doc(text: str) -> tuple[dict | None, str]:
    m = FRONT_MATTER_RE.match(text)
    if not m:
        return None, text
    meta = yaml.safe_load(m.group(1))
    return (meta if isinstance(meta, dict) else None), text[m.end() :]


def base_version_and_body(path: Path, base: str) -> tuple[str, str] | None:
    rel = path.relative_to(REPO).as_posix()
    proc = subprocess.run(
        ["git", "-C", str(REPO), "show", f"{base}:{rel}"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        return None  # file did not exist at base
    meta, body = split_doc(proc.stdout)
    if meta is None:
        return None  # pre-pilot document without front matter
    return str(meta.get("version", "")), body


def make_index(docs: list[tuple[Path, dict]]) -> str:
    lines = [
        "# ADR Index",
        "",
        "Generated by `tools/governance/adr_lint.py --write-index`. Do not edit.",
        "",
        "| ID | Title | Status | Date |",
        "|----|-------|--------|------|",
    ]
    adrs = [
        (p, m)
        for p, m in docs
        if p.is_relative_to(ADR_DIR) and str(m.get("id", "")).startswith("ADR-")
    ]
    adrs.sort(key=lambda pm: str(pm[1].get("id")))
    for p, m in adrs:
        rel = p.relative_to(ADR_DIR).as_posix()
        date = m.get("ratified") or m.get("proposed") or ""
        lines.append(
            f"| {m.get('id')} | [{m.get('title')}]({rel}) | {m.get('status')} | {date} |"
        )
    lines.append("")
    lines.append(
        "ADR-0006 (`0006-emu-reuse-and-conformance.md`) is referenced by "
        "`src/disc/NOTES.md` but was never committed; the number stays reserved."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", help="git ref to compare accepted bodies against")
    ap.add_argument("--write-index", action="store_true")
    ap.add_argument("--check-index", action="store_true")
    ap.add_argument("--fix-expiry", action="store_true")
    ap.add_argument("--json", dest="json_out", help="write findings as JSON to file")
    ap.add_argument(
        "--today", help="override today's date (YYYY-MM-DD) for reproducible runs"
    )
    args = ap.parse_args()

    today = (
        dt.date.fromisoformat(args.today) if args.today else dt.date.today()
    )
    errors: list[dict] = []
    notices: list[dict] = []
    docs: list[tuple[Path, dict]] = []
    accepted_ids: dict[str, str] = {}

    def err(path: Path, rule: str, msg: str) -> None:
        errors.append(
            {"file": path.relative_to(REPO).as_posix(), "rule": rule, "message": msg}
        )

    for path in governed_files():
        text = path.read_text(encoding="utf-8")
        meta, body = split_doc(text)
        if meta is None:
            err(path, "front-matter", "missing or unparsable YAML front matter")
            continue
        docs.append((path, meta))

        for key in ("id", "title", "status", "version"):
            if not meta.get(key):
                err(path, "required-key", f"front matter lacks `{key}`")
        status = str(meta.get("status", ""))
        doc_id = str(meta.get("id", ""))

        if status not in VALID_STATUS:
            err(path, "status-value", f"invalid status `{status}`")
            continue

        parent = path.parent.name if path.parent != REPO else "."
        if parent not in STATUS_DIRS[status]:
            err(
                path,
                "status-location",
                f"status `{status}` does not belong in `{parent}/`",
            )

        if status == "accepted":
            if not meta.get("ratified"):
                err(path, "ratified-date", "accepted document lacks `ratified` date")
            if doc_id in accepted_ids:
                err(
                    path,
                    "duplicate-accepted",
                    f"`{doc_id}` already accepted in {accepted_ids[doc_id]}",
                )
            accepted_ids[doc_id] = path.relative_to(REPO).as_posix()

        if status == "superseded" and not meta.get("superseded_by"):
            err(path, "successor", "superseded document lacks `superseded_by`")

        if status == "proposed":
            proposed = meta.get("proposed")
            if not proposed:
                err(path, "proposed-date", "proposed document lacks `proposed` date")
            else:
                age = (today - dt.date.fromisoformat(str(proposed))).days
                if age > EXPIRY_DAYS:
                    notices.append(
                        {
                            "file": path.relative_to(REPO).as_posix(),
                            "rule": "expiry",
                            "message": f"proposed {age} days ago (window {EXPIRY_DAYS}d)",
                        }
                    )
                    if args.fix_expiry:
                        path.write_text(
                            text.replace("status: proposed", "status: expired", 1),
                            encoding="utf-8",
                        )

        if args.base and status == "accepted":
            at_base = base_version_and_body(path, args.base)
            if at_base is not None:
                base_ver, base_body = at_base
                if base_body != body and base_ver == str(meta.get("version")):
                    err(
                        path,
                        "version-bump",
                        "accepted body changed without a version bump",
                    )

    index_path = ADR_DIR / "INDEX.md"
    index_text = make_index(docs)
    if args.write_index:
        index_path.write_text(index_text, encoding="utf-8")
    elif args.check_index:
        current = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
        if current != index_text:
            err(index_path, "stale-index", "INDEX.md is stale; run --write-index")

    result = {"gate": "G9", "errors": errors, "notices": notices}
    if args.json_out:
        Path(args.json_out).write_text(json.dumps(result, indent=2), encoding="utf-8")
    for n in notices:
        print(f"notice: {n['file']}: {n['rule']}: {n['message']}")
    for e in errors:
        print(f"error: {e['file']}: {e['rule']}: {e['message']}")
    print(f"adr_lint: {len(errors)} error(s), {len(notices)} notice(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
