#!/usr/bin/env python3
"""Weekly review packet (MNE-CTX-PLAN-001 §11) — zero manual assembly.

Reads the two most recent metric snapshots and emits
metrics/packets/YYYY-WW.md containing:

  - metric deltas vs. the prior snapshot
  - open proposals with their expiry countdown (H1 work queue)
  - advisory-gate findings (G11 budgets) and capsule budget headroom
  - capture-omission count (§5.2)
  - hypothesis (H1–H4) evaluation status
  - the tuning loop: the single largest tracked regression, paired with an
    auto-drafted corrective proposal under docs/adr/proposed/ — mechanical
    template only (metric, delta, trigger); the analysis is the ratifier's

The packet is the H1 work surface: one read, batched decisions.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
SNAPSHOTS = REPO / "metrics" / "snapshots"
PACKETS = REPO / "metrics" / "packets"
PROPOSED = REPO / "docs" / "adr" / "proposed"
EXPIRY_DAYS = 14
FRONT_MATTER_RE = re.compile(r"\A---\n(.*?\n)---\n", re.DOTALL)

# (key-path, label, direction) — direction "down" means lower is better.
TRACKED = [
    (("M1_capsule_drift",), "M1 capsule drift", "down"),
    (("M2_dead_references",), "M2 dead references", "down"),
    (("M3_invariant_coverage",), "M3 invariant coverage", "up"),
    (("M4_prose_only_claims", "ratio"), "M4 prose-only ratio", "down"),
    (("M8_first_pass", "rate"), "M8 first-pass acceptance", "up"),
    (("M11_determinism_divergences",), "M11 divergences", "down"),
    (("M13_proposal_expiry", "rate"), "M13 expiry rate", "down"),
    (("M16_ratifications_7d",), "M16 ratifications/wk", "down"),
]


def dig(snap: dict, path: tuple) -> object:
    cur: object = snap
    for key in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
    return cur


def latest_snapshots() -> list[dict]:
    files = sorted(SNAPSHOTS.glob("????-??-??.json"))
    return [json.loads(f.read_text(encoding="utf-8")) for f in files[-2:]]


def open_proposals(today: dt.date) -> list[dict]:
    rows = []
    for p in sorted(PROPOSED.glob("*.md")):
        m = FRONT_MATTER_RE.match(p.read_text(encoding="utf-8"))
        if not m:
            continue
        meta = yaml.safe_load(m.group(1)) or {}
        if meta.get("status") != "proposed":
            continue
        proposed = dt.date.fromisoformat(str(meta.get("proposed", today)))
        rows.append({"id": meta.get("id"), "title": meta.get("title"),
                     "days_left": EXPIRY_DAYS - (today - proposed).days})
    return rows


def next_adr_number() -> int:
    nums = [int(m.group(1))
            for d in (PROPOSED, REPO / "docs" / "adr" / "accepted",
                      REPO / "docs" / "adr" / "superseded")
            if d.is_dir()
            for p in d.glob("*.md")
            if (m := re.match(r"(\d{4})-", p.name))]
    return max(nums, default=0) + 1


def draft_corrective(today: dt.date, label: str, prev, cur) -> str:
    n = next_adr_number()
    slug = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")
    path = PROPOSED / f"{n:04d}-tuning-{slug}.md"
    path.write_text(f"""---
id: ADR-{n:04d}
title: "Tuning: {label} regressed {prev} -> {cur}"
status: proposed
version: 1.0.0
supersedes: []
superseded_by: null
proposed: {today.isoformat()}
---

# ADR {n:04d}: Tuning Proposal — {label}

Auto-drafted by `weekly_packet.py` (MNE-CTX-PLAN-001 §11 tuning loop). This
records the trigger mechanically; the diagnosis and the chosen correction
are the ratifier's to fill in or reject. Rejection is a valid outcome.

## Trigger

`{label}` moved from `{prev}` to `{cur}` between the last two snapshots —
the largest tracked regression in this packet's window.

## Proposed correction

*(to be completed at ratification — e.g. widen a capsule, split a subsystem,
tighten a contract, adjust a budget; see §13 falsification actions)*
""", encoding="utf-8")
    return path.relative_to(REPO).as_posix()


def build_packet(today: dt.date, draft: bool) -> str:
    snaps = latest_snapshots()
    cur = snaps[-1] if snaps else {}
    prev = snaps[-2] if len(snaps) > 1 else None
    week = today.isocalendar()
    lines = [
        f"# Weekly Packet — {today.isoformat()} (week {week.year}-W{week.week:02d})",
        "",
        "Generated by `tools/governance/weekly_packet.py`. Do not edit.",
        "",
        "## Metric deltas",
        "",
        "| Metric | Prev | Now | Δ |",
        "|--------|------|-----|---|",
    ]
    worst = None  # (label, prev_v, cur_v)
    for path, label, direction in TRACKED:
        cur_v = dig(cur, path)
        prev_v = dig(prev, path) if prev else None
        delta = ""
        if isinstance(cur_v, (int, float)) and isinstance(prev_v, (int, float)):
            diff = cur_v - prev_v
            regressed = diff > 0 if direction == "down" else diff < 0
            delta = f"{diff:+g}" + (" ⚠" if regressed and diff != 0 else "")
            if regressed and diff != 0:
                if worst is None or abs(diff) > abs(worst[2] - worst[1]):
                    worst = (label, prev_v, cur_v)
        lines.append(f"| {label} | {prev_v if prev_v is not None else '—'} "
                     f"| {cur_v if cur_v is not None else '—'} | {delta} |")

    lines += ["", "## H1 work queue — open proposals", ""]
    proposals = open_proposals(today)
    if proposals:
        for p in proposals:
            urgency = " **EXPIRES SOON**" if p["days_left"] <= 3 else ""
            lines.append(f"- {p['id']}: {p['title']} — {p['days_left']} day(s) "
                         f"to expiry{urgency}")
    else:
        lines.append("- (none)")

    g11 = cur.get("G11_token_budget", {})
    sess = cur.get("sessions", {})
    lines += [
        "",
        "## Advisory findings",
        "",
        f"- G11 token-budget breaches: {g11.get('breaches', '—')}",
        f"- Capture omissions (§5.2): {sess.get('capture_omissions', '—')} "
        f"across {sess.get('sessions_logged', 0)} logged session(s)",
        "",
        "## Hypothesis status (evaluated P3 + 4 weeks vs week-0 baselines)",
        "",
        "- H1 (M6 −40%): blocked on week-0 instrumented sessions + OTel ingestion",
        "- H2 (M7 < 15%): blocked on task-contract read manifests in live use",
        "- H3 (M8 ≥ 80%): measurable now — current "
        f"{dig(cur, ('M8_first_pass', 'rate'))}",
        "- H4 (M15 −50%): blocked on week-0 instrumented sessions",
        "",
        "## Tuning loop",
        "",
    ]
    if worst and draft:
        adr = draft_corrective(today, *worst)
        lines.append(f"Largest regression: **{worst[0]}** ({worst[1]} → {worst[2]}). "
                     f"Corrective proposal auto-drafted: `{adr}`.")
    elif worst:
        lines.append(f"Largest regression: **{worst[0]}** ({worst[1]} → {worst[2]}). "
                     "(run with --draft to auto-draft the corrective proposal)")
    else:
        lines.append("No tracked metric regressed against the prior snapshot.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--today")
    ap.add_argument("--draft", action="store_true",
                    help="auto-draft a corrective ADR for the largest regression")
    args = ap.parse_args()
    today = dt.date.fromisoformat(args.today) if args.today else dt.date.today()

    PACKETS.mkdir(parents=True, exist_ok=True)
    week = today.isocalendar()
    out = PACKETS / f"{week.year}-W{week.week:02d}.md"
    out.write_text(build_packet(today, args.draft), encoding="utf-8")
    print(f"weekly_packet: {out.relative_to(REPO)} written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
